on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

   
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 2500
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v3

      - name: "Java Setup"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Build Linux (arm64)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/AppDir"
          dockerRunArgs: |
            --volume "${PWD}/AppDir:/AppDir"

          install: |
            echo Installing dependencies
            apt-get update -qq -y
            apt install bash zip unzip curl file clang git sudo cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev libstdc++-12-dev xz-utils -y
            echo Installing Flutter
            git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/flutter
            /opt/flutter/bin/flutter doctor -v

          run: |
            echo Creating non-root user
            useradd -m nonroot
            chown -R nonroot /opt/flutter
            chown -R nonroot .

            echo Building
            sudo -u nonroot /opt/flutter/bin/flutter build linux --target-platform linux-arm64            

      - name: Compress Flutter build
        id: compress
        run: |
          echo "Compressing"
          archiveName="fluffychat-linux-arm64.tar.gz"
          
          sudo chown -R $USER:$USER .
          tar -C build/linux/arm64/release/bundle -czf $archiveName .

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "fluffychat-linux-arm64.tar.gz"
          commit: ${{ github.sha }}
          allowUpdates: true
